name: $(BuildDefinitionName).$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - '*'
  paths:
    include: 
      - 'vs/*'

variables:
  SqlServerInstance: '(localdb)\MSSQLLocalDB'
  TestingDbName: Sprockit

pool:
  vmImage: 'windows-2019'

steps:

- task: CopyFiles@2
  displayName: Copy SQL 2008 system DB dacpacs to correct location in build agent
  inputs:
    sourceFolder: 'vs'
    contents: '*.dacpac' 
    targetFolder: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\100\SqlSchemas\'

- task: SqlDacpacDeploymentOnMachineGroup@0
  displayName: Enable CLR on $(SqlServerInstance)  # required for tSQLt
  inputs:
    TaskType: 'sqlInline'
    InlineSql: |
      EXEC sp_configure 'clr enabled', 1;
      RECONFIGURE;
    ServerName: $(SqlServerInstance)
    DatabaseName: 'master'
    AuthScheme: 'windowsAuthentication'

- task: VSBuild@1
  displayName: 'Build SprockitTests SSDT project'
  inputs:
    solution: '**\SprockitTests.sqlproj'
    configuration: 'Debug'
    clean: true

- task: SqlDacpacDeploymentOnMachineGroup@0
  displayName: 'Deploy SprockitTests SSDT project to $(TestingDbName) DB'
  inputs:
    TaskType: 'dacpac'
    DacpacFile: 'vs\**\SprockitTests.dacpac'
    TargetMethod: server
    ServerName: $(SqlServerInstance)
    DatabaseName: $(TestingDbName)
    AuthScheme: 'windowsAuthentication'
    AdditionalArguments: '/p:IncludeCompositeObjects=true /p:CreateNewDatabase=true /v:Sprockit=Sprockit /v:tSQLt=tSQLt'

- task: SqlDacpacDeploymentOnMachineGroup@0
  displayName: Run tSQLt tests
  inputs:
    TaskType: 'sqlInline'
    InlineSql: 'EXEC tSQLt.RunAll'
    ServerName: $(SqlServerInstance)
    DatabaseName: $(TestingDbName)
    AuthScheme: 'windowsAuthentication'

- task: PowerShell@2
  displayName: Export tSQLt test results
  inputs:
    targetType: 'inline'
    script: |
      $connectionString = "Server=$(SqlServerInstance);Database=$(TestingDbName);Trusted_Connection=true;"
      $filepath = "$(System.DefaultWorkingDirectory)/testresults.xml"

      $connection = new-object system.data.SqlClient.SQLConnection($connectionString)
      $sqlCommand = 'EXEC tSQLt.XmlResultFormatter'
      
      try
      {
        $connection.Open()
        $command = new-object system.data.sqlclient.sqlcommand($sqlCommand,$connection)
        $command.CommandTimeout = 60
            
        $xmlReader = $command.ExecuteXmlReader()
            
        $xmlWriterSettings = New-Object System.Xml.XmlWriterSettings
        $xmlWriterSettings.CloseOutput = $true
        $xmlWriter = ([System.Xml.XmlWriter]::Create($filePath, $xmlWriterSettings))
        
        $xmlWriter.WriteNode($xmlReader,$true)    
        $xmlWriter.Flush()
      }
      catch {
        $errorMessage = $_.Exception.Message
        $body = "Extract failed to run for the extract: $errorMessage"
      }
      finally
      {
          $xmlWriter.Dispose()
          $xmlReader.Dispose()
          $connection.Dispose()
      }

- task: PublishTestResults@2
  displayName: Publish tSQLt test results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: '$(TestingDbName) tSQLt test results'
